DROP TABLE IF EXISTS `employee`;

CREATE TABLE `employee` (
`id` BIGINT AUTO_INCREMENT,
`firstname` VARCHAR(255) NOT NULL,
`last_name` VARCHAR(255) NOT NULL,
`department` VARCHAR(255) NOT NULL,
`ADDRESS` VARCHAR(255) NOT NULL,
`email` VARCHAR(255) UNIQUE NOT NULL,
PRIMARY KEY(`id`)
);

